version: "3.8"
services:
  master:
    image: mysql:5.7.32
    hostname: master
    environment:
      - MYSQL_USER=admin  #创建用户
      - MYSQL_PASSWORD=123qwe  #用户密码
      - MYSQL_ROOT_PASSWORD=1qaztyui #root 用户密码
      - TZ=Asia/Shanghai
    volumes:
      - ./master/conf.d:/etc/mysql/conf.d
      - ./master/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./master/data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 10000M
      replicas: 1

  slave1:
    image: mysql:5.7.32
    hostname: slave1
    environment:
      - MYSQL_USER=admin  #创建用户
      - MYSQL_PASSWORD=123qwe  #用户密码
      - MYSQL_ROOT_PASSWORD=1qaztyui #root 用户密码
      - TZ=Asia/Shanghai
    volumes:
      - ./master/conf.d:/etc/mysql/conf.d
      - ./master/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./master/data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 10000M
      replicas: 1

  slave2:
    image: mysql:5.7.32
    hostname: slave2
    environment:
      - MYSQL_USER=admin  #创建用户
      - MYSQL_PASSWORD=123qwe  #用户密码
      - MYSQL_ROOT_PASSWORD=1qaztyui #root 用户密码
      - TZ=Asia/Shanghai
    volumes:
      - ./master/conf.d:/etc/mysql/conf.d
      - ./master/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./master/data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 10000M
      replicas: 1

networks:
  mysql:
